/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Leo
 */
public class f_Main extends javax.swing.JFrame {

    /**
     * Creates new form f_Main
     */
    public f_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_EaSynth = new javax.swing.JButton();
        jb_LiquidLnF = new javax.swing.JButton();
        javax.swing.JButton jb_FlatLaf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_EaSynth.setLabel("EaSynth");
        jb_EaSynth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_EaSynth(evt);
            }
        });

        jb_LiquidLnF.setText("LiquidLnf");
        jb_LiquidLnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_LiquidLnf(evt);
            }
        });

        jb_FlatLaf.setLabel("FlatLaf");
        jb_FlatLaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_FlatIntelliJLaf(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_FlatLaf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_LiquidLnF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_EaSynth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jb_EaSynth)
                .addGap(18, 18, 18)
                .addComponent(jb_LiquidLnF)
                .addGap(18, 18, 18)
                .addComponent(jb_FlatLaf)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show_EaSynth(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_EaSynth
        jf_LookAndFeel EaSynth = new jf_LookAndFeel();
        try {                   
            UIManager.setLookAndFeel("com.easynth.lookandfeel.EaSynthLookAndFeel");                
        } catch( Exception ex ) {
            System.err.println( "EaSynth Look And Feel" );
        }
        SwingUtilities.updateComponentTreeUI(EaSynth );
        EaSynth.setVisible(true);        
    }//GEN-LAST:event_Show_EaSynth

    private void Show_FlatIntelliJLaf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_FlatIntelliJLaf
        jf_LookAndFeel FlatLaf = new jf_LookAndFeel();
        try {                   
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatIntelliJLaf");                
        } catch( Exception ex ) {
            System.err.println( "FlatLaf Look And Feel" );
        }
        SwingUtilities.updateComponentTreeUI(FlatLaf );
        FlatLaf.setVisible(true);
    }//GEN-LAST:event_Show_FlatIntelliJLaf

    private void Show_LiquidLnf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_LiquidLnf
        jf_LookAndFeel LiquidLnf = new jf_LookAndFeel();
        try {                   
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel" );                
        } catch( Exception ex ) {
            System.err.println( "FlatLaf Look And Feel" );
        }
        SwingUtilities.updateComponentTreeUI(LiquidLnf );
        LiquidLnf.setVisible(true);
    }//GEN-LAST:event_Show_LiquidLnf

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_EaSynth;
    private javax.swing.JButton jb_LiquidLnF;
    // End of variables declaration//GEN-END:variables
}
